name: Run tests

on:
  push:
    branches:
      - alpha
  pull_request:
    branches:
      - alpha
    
env:
  BYOND_MAJOR: 513
  BYOND_MINOR: 1536
    
jobs:
  code-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TEST: [CODE, WEB]
    timeout-minutes: 20
    env:
      TEST: ${{ matrix.TEST }}
      MAP_PATH: ${{ matrix.MAPPATH }}
      
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            tgui/node_modules
          key: ${{ runner.os }}-tgui-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install gcc-multilib g++-multilib openjdk-11-jdk
      - name: Run tests
        run: bash test/run-test.sh
  map-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        MAPPATH:
          - operation_trebuchet
          - slayer
          - firefight
          - crusade
          - stranded
          - first_contact
          - ks7_elmsville
          - ks7_elmsville_spaceodp
          - base_assault
          #- example
          #- first_contact
          #- geminus_city
          #- overmap_example
    
    timeout-minutes: 20
    env:
      TEST: MAP
      MAP_PATH: ${{ matrix.MAPPATH }}
      
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            tgui/node_modules
            ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install gcc-multilib g++-multilib openjdk-11-jdk
      - name: Run tests
        run: bash test/run-test.sh
